config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
  resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    # 指定のユーザがフォローしている全員を表示する
      get 'followings' => 'relationships#followings', as: 'followings'
    # 指定のユーザをフォローしている全員を表示する
      get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # いいねを押す前の画面に戻る
    #redirect_to request.referer
    #非同期化のためにコメントアウト
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_to request.referer
    #非同期化のためにコメントアウト
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<!--一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ-->
  <% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book.id)  , method: :delete, remote: true do %>
    <span style="color:red;">♥︎</span><%= book.favorites.count %>
    <% end %>
  </p>

<!--一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ-->
  <% else %>
  <p>
    <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
      <span>♥</span><%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorites", book: @book) %>");